// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking_options.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearBookingTodoWinner = `-- name: ClearBookingTodoWinner :many
UPDATE booking_options
SET promoted_accommodation_id = NULL, promoted_segment_id = NULL
WHERE booking_todo_id = $1
  AND (promoted_accommodation_id IS NOT NULL OR promoted_segment_id IS NOT NULL)
RETURNING id
`

// Un-stamps whichever option currently wins this leg. Runs first inside the
// choose transaction so idx_booking_options_winner stays a backstop against a
// concurrent double-choose rather than the mechanism, and returns the id so the
// response can name what it replaced.
func (q *Queries) ClearBookingTodoWinner(ctx context.Context, bookingTodoID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, clearBookingTodoWinner, bookingTodoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBookingOptionsByTodo = `-- name: CountBookingOptionsByTodo :one
SELECT count(*) FROM booking_options WHERE booking_todo_id = $1
`

func (q *Queries) CountBookingOptionsByTodo(ctx context.Context, bookingTodoID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBookingOptionsByTodo, bookingTodoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBookingOptionsByTrip = `-- name: CountBookingOptionsByTrip :one
SELECT count(*) FROM booking_options WHERE trip_id = $1
`

func (q *Queries) CountBookingOptionsByTrip(ctx context.Context, tripID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBookingOptionsByTrip, tripID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBookingOption = `-- name: CreateBookingOption :one
INSERT INTO booking_options (
    trip_id, booking_todo_id, title, subtitle, url, provider, notes, image_url,
    price, currency, start_date, end_date, origin, destination, mode, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15,
        COALESCE((SELECT max(position) + 1 FROM booking_options WHERE booking_todo_id = $2), 0))
RETURNING id, trip_id, booking_todo_id, title, subtitle, url, provider, notes, image_url, price, currency, start_date, end_date, origin, destination, mode, promoted_accommodation_id, promoted_segment_id, position, created_at, updated_at
`

type CreateBookingOptionParams struct {
	TripID        uuid.UUID   `json:"trip_id"`
	BookingTodoID uuid.UUID   `json:"booking_todo_id"`
	Title         string      `json:"title"`
	Subtitle      *string     `json:"subtitle"`
	Url           *string     `json:"url"`
	Provider      *string     `json:"provider"`
	Notes         *string     `json:"notes"`
	ImageUrl      *string     `json:"image_url"`
	Price         *float64    `json:"price"`
	Currency      *string     `json:"currency"`
	StartDate     pgtype.Date `json:"start_date"`
	EndDate       pgtype.Date `json:"end_date"`
	Origin        *string     `json:"origin"`
	Destination   *string     `json:"destination"`
	Mode          *string     `json:"mode"`
}

func (q *Queries) CreateBookingOption(ctx context.Context, arg CreateBookingOptionParams) (BookingOption, error) {
	row := q.db.QueryRow(ctx, createBookingOption,
		arg.TripID,
		arg.BookingTodoID,
		arg.Title,
		arg.Subtitle,
		arg.Url,
		arg.Provider,
		arg.Notes,
		arg.ImageUrl,
		arg.Price,
		arg.Currency,
		arg.StartDate,
		arg.EndDate,
		arg.Origin,
		arg.Destination,
		arg.Mode,
	)
	var i BookingOption
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.BookingTodoID,
		&i.Title,
		&i.Subtitle,
		&i.Url,
		&i.Provider,
		&i.Notes,
		&i.ImageUrl,
		&i.Price,
		&i.Currency,
		&i.StartDate,
		&i.EndDate,
		&i.Origin,
		&i.Destination,
		&i.Mode,
		&i.PromotedAccommodationID,
		&i.PromotedSegmentID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBookingOption = `-- name: DeleteBookingOption :execrows
DELETE FROM booking_options
WHERE id = $1 AND trip_id = $2
  AND promoted_accommodation_id IS NULL AND promoted_segment_id IS NULL
`

type DeleteBookingOptionParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

// Refuses a CHOSEN option. Removing a bookmark must not silently unbook a leg
// and delete its expense as a side effect (docs/zen.md: errors should never
// pass silently) — the handler turns the zero row count into a 409 telling the
// caller to un-choose first.
func (q *Queries) DeleteBookingOption(ctx context.Context, arg DeleteBookingOptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBookingOption, arg.ID, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBookingOption = `-- name: GetBookingOption :one
SELECT id, trip_id, booking_todo_id, title, subtitle, url, provider, notes, image_url, price, currency, start_date, end_date, origin, destination, mode, promoted_accommodation_id, promoted_segment_id, position, created_at, updated_at FROM booking_options WHERE id = $1 AND trip_id = $2
`

type GetBookingOptionParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

func (q *Queries) GetBookingOption(ctx context.Context, arg GetBookingOptionParams) (BookingOption, error) {
	row := q.db.QueryRow(ctx, getBookingOption, arg.ID, arg.TripID)
	var i BookingOption
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.BookingTodoID,
		&i.Title,
		&i.Subtitle,
		&i.Url,
		&i.Provider,
		&i.Notes,
		&i.ImageUrl,
		&i.Price,
		&i.Currency,
		&i.StartDate,
		&i.EndDate,
		&i.Origin,
		&i.Destination,
		&i.Mode,
		&i.PromotedAccommodationID,
		&i.PromotedSegmentID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookingOptionsByTodo = `-- name: ListBookingOptionsByTodo :many
SELECT id, trip_id, booking_todo_id, title, subtitle, url, provider, notes, image_url, price, currency, start_date, end_date, origin, destination, mode, promoted_accommodation_id, promoted_segment_id, position, created_at, updated_at FROM booking_options
WHERE booking_todo_id = $1
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListBookingOptionsByTodo(ctx context.Context, bookingTodoID uuid.UUID) ([]BookingOption, error) {
	rows, err := q.db.Query(ctx, listBookingOptionsByTodo, bookingTodoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingOption
	for rows.Next() {
		var i BookingOption
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.BookingTodoID,
			&i.Title,
			&i.Subtitle,
			&i.Url,
			&i.Provider,
			&i.Notes,
			&i.ImageUrl,
			&i.Price,
			&i.Currency,
			&i.StartDate,
			&i.EndDate,
			&i.Origin,
			&i.Destination,
			&i.Mode,
			&i.PromotedAccommodationID,
			&i.PromotedSegmentID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingOptionsByTrip = `-- name: ListBookingOptionsByTrip :many
SELECT id, trip_id, booking_todo_id, title, subtitle, url, provider, notes, image_url, price, currency, start_date, end_date, origin, destination, mode, promoted_accommodation_id, promoted_segment_id, position, created_at, updated_at FROM booking_options
WHERE trip_id = $1
ORDER BY position ASC, created_at ASC
`

// The whole trip's shortlist, ordered the way it renders: by leg (the client
// groups on booking_todo_id), then manual position, then age.
func (q *Queries) ListBookingOptionsByTrip(ctx context.Context, tripID uuid.UUID) ([]BookingOption, error) {
	rows, err := q.db.Query(ctx, listBookingOptionsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingOption
	for rows.Next() {
		var i BookingOption
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.BookingTodoID,
			&i.Title,
			&i.Subtitle,
			&i.Url,
			&i.Provider,
			&i.Notes,
			&i.ImageUrl,
			&i.Price,
			&i.Currency,
			&i.StartDate,
			&i.EndDate,
			&i.Origin,
			&i.Destination,
			&i.Mode,
			&i.PromotedAccommodationID,
			&i.PromotedSegmentID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBookingOptionPromotion = `-- name: SetBookingOptionPromotion :one
UPDATE booking_options
SET promoted_accommodation_id = $3, promoted_segment_id = $4
WHERE id = $1 AND trip_id = $2
RETURNING id, trip_id, booking_todo_id, title, subtitle, url, provider, notes, image_url, price, currency, start_date, end_date, origin, destination, mode, promoted_accommodation_id, promoted_segment_id, position, created_at, updated_at
`

type SetBookingOptionPromotionParams struct {
	ID                      uuid.UUID   `json:"id"`
	TripID                  uuid.UUID   `json:"trip_id"`
	PromotedAccommodationID pgtype.UUID `json:"promoted_accommodation_id"`
	PromotedSegmentID       pgtype.UUID `json:"promoted_segment_id"`
}

func (q *Queries) SetBookingOptionPromotion(ctx context.Context, arg SetBookingOptionPromotionParams) (BookingOption, error) {
	row := q.db.QueryRow(ctx, setBookingOptionPromotion,
		arg.ID,
		arg.TripID,
		arg.PromotedAccommodationID,
		arg.PromotedSegmentID,
	)
	var i BookingOption
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.BookingTodoID,
		&i.Title,
		&i.Subtitle,
		&i.Url,
		&i.Provider,
		&i.Notes,
		&i.ImageUrl,
		&i.Price,
		&i.Currency,
		&i.StartDate,
		&i.EndDate,
		&i.Origin,
		&i.Destination,
		&i.Mode,
		&i.PromotedAccommodationID,
		&i.PromotedSegmentID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBookingOption = `-- name: UpdateBookingOption :one
UPDATE booking_options
SET title       = COALESCE($1, title),
    subtitle    = COALESCE($2, subtitle),
    url         = COALESCE($3, url),
    provider    = COALESCE($4, provider),
    notes       = COALESCE($5, notes),
    image_url   = COALESCE($6, image_url),
    price       = COALESCE($7, price),
    currency    = COALESCE($8, currency),
    start_date  = COALESCE($9, start_date),
    end_date    = COALESCE($10, end_date),
    origin      = COALESCE($11, origin),
    destination = COALESCE($12, destination),
    mode        = COALESCE($13, mode)
WHERE id = $14 AND trip_id = $15
RETURNING id, trip_id, booking_todo_id, title, subtitle, url, provider, notes, image_url, price, currency, start_date, end_date, origin, destination, mode, promoted_accommodation_id, promoted_segment_id, position, created_at, updated_at
`

type UpdateBookingOptionParams struct {
	Title       *string     `json:"title"`
	Subtitle    *string     `json:"subtitle"`
	Url         *string     `json:"url"`
	Provider    *string     `json:"provider"`
	Notes       *string     `json:"notes"`
	ImageUrl    *string     `json:"image_url"`
	Price       *float64    `json:"price"`
	Currency    *string     `json:"currency"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	Origin      *string     `json:"origin"`
	Destination *string     `json:"destination"`
	Mode        *string     `json:"mode"`
	ID          uuid.UUID   `json:"id"`
	TripID      uuid.UUID   `json:"trip_id"`
}

// Partial update (COALESCE sqlc.narg idiom, see query/trips.sql UpdateTrip).
// COALESCE means fields can be overwritten but not cleared back to NULL.
//
// The promoted_* columns are deliberately absent: "which option won" is set by
// the choose transaction alone, never by a client PATCH. Same shape as
// booking_todos.auto — one writer, named.
func (q *Queries) UpdateBookingOption(ctx context.Context, arg UpdateBookingOptionParams) (BookingOption, error) {
	row := q.db.QueryRow(ctx, updateBookingOption,
		arg.Title,
		arg.Subtitle,
		arg.Url,
		arg.Provider,
		arg.Notes,
		arg.ImageUrl,
		arg.Price,
		arg.Currency,
		arg.StartDate,
		arg.EndDate,
		arg.Origin,
		arg.Destination,
		arg.Mode,
		arg.ID,
		arg.TripID,
	)
	var i BookingOption
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.BookingTodoID,
		&i.Title,
		&i.Subtitle,
		&i.Url,
		&i.Provider,
		&i.Notes,
		&i.ImageUrl,
		&i.Price,
		&i.Currency,
		&i.StartDate,
		&i.EndDate,
		&i.Origin,
		&i.Destination,
		&i.Mode,
		&i.PromotedAccommodationID,
		&i.PromotedSegmentID,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
