// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForCreateItineraryItems implements pgx.CopyFromSource.
type iteratorForCreateItineraryItems struct {
	rows                 []CreateItineraryItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateItineraryItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateItineraryItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TripID,
		r.rows[0].Position,
		r.rows[0].Name,
		r.rows[0].PlaceID,
		r.rows[0].Address,
		r.rows[0].Latitude,
		r.rows[0].Longitude,
		r.rows[0].Category,
		r.rows[0].TimeOfDay,
		r.rows[0].City,
		r.rows[0].DayTripFrom,
		r.rows[0].Day,
		r.rows[0].LocalSourceName,
		r.rows[0].LocalRecommendationID,
	}, nil
}

func (r iteratorForCreateItineraryItems) Err() error {
	return nil
}

// Bulk twin of CreateItineraryItem (agent itinerary save — the per-row
// results were discarded, so COPY is safe). Same column list; id/created_at
// keep their defaults.
func (q *Queries) CreateItineraryItems(ctx context.Context, arg []CreateItineraryItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"itinerary_items"}, []string{"trip_id", "position", "name", "place_id", "address", "latitude", "longitude", "category", "time_of_day", "city", "day_trip_from", "day", "local_source_name", "local_recommendation_id"}, &iteratorForCreateItineraryItems{rows: arg})
}
