// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: itinerary_items.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateItineraryItemsParams struct {
	TripID                uuid.UUID   `json:"trip_id"`
	Position              int32       `json:"position"`
	Name                  string      `json:"name"`
	PlaceID               *string     `json:"place_id"`
	Address               *string     `json:"address"`
	Latitude              float64     `json:"latitude"`
	Longitude             float64     `json:"longitude"`
	Category              *string     `json:"category"`
	TimeOfDay             *string     `json:"time_of_day"`
	City                  *string     `json:"city"`
	DayTripFrom           *string     `json:"day_trip_from"`
	Day                   *int32      `json:"day"`
	LocalSourceName       *string     `json:"local_source_name"`
	LocalRecommendationID pgtype.UUID `json:"local_recommendation_id"`
}

const setItineraryItemPositionsBatch = `-- name: SetItineraryItemPositionsBatch :exec

UPDATE itinerary_items i
SET position = u.pos
FROM (
    SELECT unnest($2::uuid[])      AS id,
           unnest($3::int[]) AS pos
) AS u
WHERE i.id = u.id AND i.trip_id = $1::uuid
`

type SetItineraryItemPositionsBatchParams struct {
	TripID    uuid.UUID   `json:"trip_id"`
	Ids       []uuid.UUID `json:"ids"`
	Positions []int32     `json:"positions"`
}

// Batch statements for itinerary items (perf: replace per-row write loops
// with one round trip). The non-batch item queries live in query/trips.sql.
// One round trip for the whole reorder. ids and positions are parallel
// arrays; every row is scoped to trip_id so a foreign id can never move
// another trip's row.
func (q *Queries) SetItineraryItemPositionsBatch(ctx context.Context, arg SetItineraryItemPositionsBatchParams) error {
	_, err := q.db.Exec(ctx, setItineraryItemPositionsBatch, arg.TripID, arg.Ids, arg.Positions)
	return err
}
