// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveOAuthAuthRequest = `-- name: ApproveOAuthAuthRequest :one
UPDATE oauth_auth_codes
SET user_id = $2, code_hash = $3, approved_at = now(), expires_at = $4
WHERE request_token_hash = $1 AND approved_at IS NULL AND expires_at > now()
RETURNING id, client_id, request_token_hash, redirect_uri, scope, state, code_challenge, user_id, code_hash, approved_at, code_used_at, expires_at, created_at
`

type ApproveOAuthAuthRequestParams struct {
	RequestTokenHash string      `json:"request_token_hash"`
	UserID           pgtype.UUID `json:"user_id"`
	CodeHash         *string     `json:"code_hash"`
	ExpiresAt        time.Time   `json:"expires_at"`
}

// ApproveOAuthAuthRequest binds the signed-in user and mints the code, but
// only on a still-pending, unexpired request (approved_at IS NULL makes the
// consent handle single-use).
func (q *Queries) ApproveOAuthAuthRequest(ctx context.Context, arg ApproveOAuthAuthRequestParams) (OauthAuthCode, error) {
	row := q.db.QueryRow(ctx, approveOAuthAuthRequest,
		arg.RequestTokenHash,
		arg.UserID,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i OauthAuthCode
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.RequestTokenHash,
		&i.RedirectUri,
		&i.Scope,
		&i.State,
		&i.CodeChallenge,
		&i.UserID,
		&i.CodeHash,
		&i.ApprovedAt,
		&i.CodeUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthAuthRequest = `-- name: CreateOAuthAuthRequest :one
INSERT INTO oauth_auth_codes
    (client_id, request_token_hash, redirect_uri, scope, state, code_challenge, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, client_id, request_token_hash, redirect_uri, scope, state, code_challenge, user_id, code_hash, approved_at, code_used_at, expires_at, created_at
`

type CreateOAuthAuthRequestParams struct {
	ClientID         uuid.UUID `json:"client_id"`
	RequestTokenHash string    `json:"request_token_hash"`
	RedirectUri      string    `json:"redirect_uri"`
	Scope            string    `json:"scope"`
	State            string    `json:"state"`
	CodeChallenge    string    `json:"code_challenge"`
	ExpiresAt        time.Time `json:"expires_at"`
}

func (q *Queries) CreateOAuthAuthRequest(ctx context.Context, arg CreateOAuthAuthRequestParams) (OauthAuthCode, error) {
	row := q.db.QueryRow(ctx, createOAuthAuthRequest,
		arg.ClientID,
		arg.RequestTokenHash,
		arg.RedirectUri,
		arg.Scope,
		arg.State,
		arg.CodeChallenge,
		arg.ExpiresAt,
	)
	var i OauthAuthCode
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.RequestTokenHash,
		&i.RedirectUri,
		&i.Scope,
		&i.State,
		&i.CodeChallenge,
		&i.UserID,
		&i.CodeHash,
		&i.ApprovedAt,
		&i.CodeUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthClient = `-- name: CreateOAuthClient :one

INSERT INTO oauth_clients (client_name, redirect_uris)
VALUES ($1, $2)
RETURNING id, client_name, redirect_uris, token_endpoint_auth_method, created_at, last_used_at
`

type CreateOAuthClientParams struct {
	ClientName   string   `json:"client_name"`
	RedirectUris []string `json:"redirect_uris"`
}

// OAuth 2.1 provider queries for the MCP connector (specs/mcp-connector).
// Every *_hash parameter is a SHA-256 hex digest (hashBearerToken) — raw
// tokens never reach the database.
func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, createOAuthClient, arg.ClientName, arg.RedirectUris)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.RedirectUris,
		&i.TokenEndpointAuthMethod,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createOAuthTokenPair = `-- name: CreateOAuthTokenPair :one
INSERT INTO oauth_tokens
    (grant_id, auth_code_id, access_token_hash, refresh_token_hash, access_expires_at, refresh_expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, grant_id, auth_code_id, access_token_hash, refresh_token_hash, access_expires_at, refresh_expires_at, revoked_at, created_at
`

type CreateOAuthTokenPairParams struct {
	GrantID          uuid.UUID   `json:"grant_id"`
	AuthCodeID       pgtype.UUID `json:"auth_code_id"`
	AccessTokenHash  string      `json:"access_token_hash"`
	RefreshTokenHash string      `json:"refresh_token_hash"`
	AccessExpiresAt  time.Time   `json:"access_expires_at"`
	RefreshExpiresAt time.Time   `json:"refresh_expires_at"`
}

func (q *Queries) CreateOAuthTokenPair(ctx context.Context, arg CreateOAuthTokenPairParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, createOAuthTokenPair,
		arg.GrantID,
		arg.AuthCodeID,
		arg.AccessTokenHash,
		arg.RefreshTokenHash,
		arg.AccessExpiresAt,
		arg.RefreshExpiresAt,
	)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.GrantID,
		&i.AuthCodeID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredOAuthAuthCodes = `-- name: DeleteExpiredOAuthAuthCodes :exec
DELETE FROM oauth_auth_codes
WHERE expires_at < now() - INTERVAL '1 day'
`

// Opportunistic janitors (the DeleteExpiredSessions pattern): auth requests
// and codes are minutes-lived; token rows become garbage after refresh expiry.
func (q *Queries) DeleteExpiredOAuthAuthCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthAuthCodes)
	return err
}

const deleteExpiredOAuthTokens = `-- name: DeleteExpiredOAuthTokens :exec
DELETE FROM oauth_tokens
WHERE refresh_expires_at < now()
`

func (q *Queries) DeleteExpiredOAuthTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthTokens)
	return err
}

const deleteOAuthAuthRequest = `-- name: DeleteOAuthAuthRequest :exec
DELETE FROM oauth_auth_codes WHERE request_token_hash = $1
`

func (q *Queries) DeleteOAuthAuthRequest(ctx context.Context, requestTokenHash string) error {
	_, err := q.db.Exec(ctx, deleteOAuthAuthRequest, requestTokenHash)
	return err
}

const getOAuthAuthCodeByCodeHash = `-- name: GetOAuthAuthCodeByCodeHash :one
SELECT id, client_id, request_token_hash, redirect_uri, scope, state, code_challenge, user_id, code_hash, approved_at, code_used_at, expires_at, created_at FROM oauth_auth_codes WHERE code_hash = $1
`

// GetOAuthAuthCodeByCodeHash intentionally returns used/expired rows too —
// the token endpoint must distinguish "unknown code" from "code reuse" (which
// revokes the tokens the first use minted).
func (q *Queries) GetOAuthAuthCodeByCodeHash(ctx context.Context, codeHash *string) (OauthAuthCode, error) {
	row := q.db.QueryRow(ctx, getOAuthAuthCodeByCodeHash, codeHash)
	var i OauthAuthCode
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.RequestTokenHash,
		&i.RedirectUri,
		&i.Scope,
		&i.State,
		&i.CodeChallenge,
		&i.UserID,
		&i.CodeHash,
		&i.ApprovedAt,
		&i.CodeUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthAuthRequestByRequestHash = `-- name: GetOAuthAuthRequestByRequestHash :one
SELECT ac.id, ac.client_id, ac.request_token_hash, ac.redirect_uri, ac.scope, ac.state, ac.code_challenge, ac.user_id, ac.code_hash, ac.approved_at, ac.code_used_at, ac.expires_at, ac.created_at, c.client_name
FROM oauth_auth_codes ac
JOIN oauth_clients c ON c.id = ac.client_id
WHERE ac.request_token_hash = $1 AND ac.expires_at > now()
`

type GetOAuthAuthRequestByRequestHashRow struct {
	ID               uuid.UUID          `json:"id"`
	ClientID         uuid.UUID          `json:"client_id"`
	RequestTokenHash string             `json:"request_token_hash"`
	RedirectUri      string             `json:"redirect_uri"`
	Scope            string             `json:"scope"`
	State            string             `json:"state"`
	CodeChallenge    string             `json:"code_challenge"`
	UserID           pgtype.UUID        `json:"user_id"`
	CodeHash         *string            `json:"code_hash"`
	ApprovedAt       pgtype.Timestamptz `json:"approved_at"`
	CodeUsedAt       pgtype.Timestamptz `json:"code_used_at"`
	ExpiresAt        time.Time          `json:"expires_at"`
	CreatedAt        time.Time          `json:"created_at"`
	ClientName       string             `json:"client_name"`
}

func (q *Queries) GetOAuthAuthRequestByRequestHash(ctx context.Context, requestTokenHash string) (GetOAuthAuthRequestByRequestHashRow, error) {
	row := q.db.QueryRow(ctx, getOAuthAuthRequestByRequestHash, requestTokenHash)
	var i GetOAuthAuthRequestByRequestHashRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.RequestTokenHash,
		&i.RedirectUri,
		&i.Scope,
		&i.State,
		&i.CodeChallenge,
		&i.UserID,
		&i.CodeHash,
		&i.ApprovedAt,
		&i.CodeUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ClientName,
	)
	return i, err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT id, client_name, redirect_uris, token_endpoint_auth_method, created_at, last_used_at FROM oauth_clients WHERE id = $1
`

func (q *Queries) GetOAuthClient(ctx context.Context, id uuid.UUID) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClient, id)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.RedirectUris,
		&i.TokenEndpointAuthMethod,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getOAuthGrantByUserAndClient = `-- name: GetOAuthGrantByUserAndClient :one
SELECT id, user_id, client_id, scope, created_at, last_used_at, revoked_at FROM oauth_grants WHERE user_id = $1 AND client_id = $2
`

type GetOAuthGrantByUserAndClientParams struct {
	UserID   uuid.UUID `json:"user_id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) GetOAuthGrantByUserAndClient(ctx context.Context, arg GetOAuthGrantByUserAndClientParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, getOAuthGrantByUserAndClient, arg.UserID, arg.ClientID)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getOAuthTokenByRefreshHash = `-- name: GetOAuthTokenByRefreshHash :one
SELECT t.id, t.grant_id, t.auth_code_id, t.access_token_hash, t.refresh_token_hash, t.access_expires_at, t.refresh_expires_at, t.revoked_at, t.created_at, g.user_id, g.scope, g.client_id, g.revoked_at AS grant_revoked_at
FROM oauth_tokens t
JOIN oauth_grants g ON g.id = t.grant_id
WHERE t.refresh_token_hash = $1
  AND t.revoked_at IS NULL
  AND t.refresh_expires_at > now()
`

type GetOAuthTokenByRefreshHashRow struct {
	ID               uuid.UUID          `json:"id"`
	GrantID          uuid.UUID          `json:"grant_id"`
	AuthCodeID       pgtype.UUID        `json:"auth_code_id"`
	AccessTokenHash  string             `json:"access_token_hash"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	AccessExpiresAt  time.Time          `json:"access_expires_at"`
	RefreshExpiresAt time.Time          `json:"refresh_expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UserID           uuid.UUID          `json:"user_id"`
	Scope            string             `json:"scope"`
	ClientID         uuid.UUID          `json:"client_id"`
	GrantRevokedAt   pgtype.Timestamptz `json:"grant_revoked_at"`
}

func (q *Queries) GetOAuthTokenByRefreshHash(ctx context.Context, refreshTokenHash string) (GetOAuthTokenByRefreshHashRow, error) {
	row := q.db.QueryRow(ctx, getOAuthTokenByRefreshHash, refreshTokenHash)
	var i GetOAuthTokenByRefreshHashRow
	err := row.Scan(
		&i.ID,
		&i.GrantID,
		&i.AuthCodeID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UserID,
		&i.Scope,
		&i.ClientID,
		&i.GrantRevokedAt,
	)
	return i, err
}

const getOAuthTokenWithUserByAccessHash = `-- name: GetOAuthTokenWithUserByAccessHash :one
SELECT t.id AS token_id, t.grant_id, g.scope, g.client_id,
       u.id, u.created_at, u.updated_at, u.email, u.password_hash, u.display_name, u.is_admin, u.onboarded_at, u.email_verified_at, u.reminders_opt_out, u.nudges_opt_out, u.last_weekly_nudge_at, u.locale
FROM oauth_tokens t
JOIN oauth_grants g ON g.id = t.grant_id
JOIN users u ON u.id = g.user_id
WHERE t.access_token_hash = $1
  AND t.revoked_at IS NULL
  AND t.access_expires_at > now()
  AND g.revoked_at IS NULL
`

type GetOAuthTokenWithUserByAccessHashRow struct {
	TokenID  uuid.UUID `json:"token_id"`
	GrantID  uuid.UUID `json:"grant_id"`
	Scope    string    `json:"scope"`
	ClientID uuid.UUID `json:"client_id"`
	User     User      `json:"user"`
}

// GetOAuthTokenWithUserByAccessHash is the /mcp auth lookup: token → grant →
// user in one round trip, filtering every revocation/expiry dimension
// (mirrors GetSessionWithUser).
func (q *Queries) GetOAuthTokenWithUserByAccessHash(ctx context.Context, accessTokenHash string) (GetOAuthTokenWithUserByAccessHashRow, error) {
	row := q.db.QueryRow(ctx, getOAuthTokenWithUserByAccessHash, accessTokenHash)
	var i GetOAuthTokenWithUserByAccessHashRow
	err := row.Scan(
		&i.TokenID,
		&i.GrantID,
		&i.Scope,
		&i.ClientID,
		&i.User.ID,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.DisplayName,
		&i.User.IsAdmin,
		&i.User.OnboardedAt,
		&i.User.EmailVerifiedAt,
		&i.User.RemindersOptOut,
		&i.User.NudgesOptOut,
		&i.User.LastWeeklyNudgeAt,
		&i.User.Locale,
	)
	return i, err
}

const listOAuthConnectionsByUser = `-- name: ListOAuthConnectionsByUser :many
SELECT g.id, g.scope, g.created_at, g.last_used_at, c.client_name
FROM oauth_grants g
JOIN oauth_clients c ON c.id = g.client_id
WHERE g.user_id = $1 AND g.revoked_at IS NULL
ORDER BY g.created_at DESC
`

type ListOAuthConnectionsByUserRow struct {
	ID         uuid.UUID          `json:"id"`
	Scope      string             `json:"scope"`
	CreatedAt  time.Time          `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ClientName string             `json:"client_name"`
}

// ListOAuthConnectionsByUser powers the Connected-apps settings section.
func (q *Queries) ListOAuthConnectionsByUser(ctx context.Context, userID uuid.UUID) ([]ListOAuthConnectionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listOAuthConnectionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOAuthConnectionsByUserRow
	for rows.Next() {
		var i ListOAuthConnectionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOAuthCodeUsed = `-- name: MarkOAuthCodeUsed :exec
UPDATE oauth_auth_codes SET code_used_at = now() WHERE id = $1
`

func (q *Queries) MarkOAuthCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOAuthCodeUsed, id)
	return err
}

const revokeOAuthGrant = `-- name: RevokeOAuthGrant :one
UPDATE oauth_grants SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
RETURNING id, user_id, client_id, scope, created_at, last_used_at, revoked_at
`

type RevokeOAuthGrantParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// RevokeOAuthGrant is owner-scoped (the WHERE user_id) — the Connected-apps
// kill switch. Token revocation is a separate statement in the same tx.
func (q *Queries) RevokeOAuthGrant(ctx context.Context, arg RevokeOAuthGrantParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, revokeOAuthGrant, arg.ID, arg.UserID)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeOAuthToken = `-- name: RevokeOAuthToken :exec
UPDATE oauth_tokens SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeOAuthToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeOAuthToken, id)
	return err
}

const revokeOAuthTokensByAuthCode = `-- name: RevokeOAuthTokensByAuthCode :exec
UPDATE oauth_tokens SET revoked_at = now() WHERE auth_code_id = $1 AND revoked_at IS NULL
`

// RevokeOAuthTokensByAuthCode backs the code-reuse response: a second
// redemption of the same code revokes everything the first minted.
func (q *Queries) RevokeOAuthTokensByAuthCode(ctx context.Context, authCodeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeOAuthTokensByAuthCode, authCodeID)
	return err
}

const revokeOAuthTokensByGrant = `-- name: RevokeOAuthTokensByGrant :exec
UPDATE oauth_tokens SET revoked_at = now() WHERE grant_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeOAuthTokensByGrant(ctx context.Context, grantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeOAuthTokensByGrant, grantID)
	return err
}

const touchOAuthClient = `-- name: TouchOAuthClient :exec
UPDATE oauth_clients SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchOAuthClient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchOAuthClient, id)
	return err
}

const touchOAuthGrant = `-- name: TouchOAuthGrant :exec
UPDATE oauth_grants SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchOAuthGrant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchOAuthGrant, id)
	return err
}

const upsertOAuthGrant = `-- name: UpsertOAuthGrant :one
INSERT INTO oauth_grants (user_id, client_id, scope)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, client_id)
DO UPDATE SET scope = EXCLUDED.scope, revoked_at = NULL
RETURNING id, user_id, client_id, scope, created_at, last_used_at, revoked_at
`

type UpsertOAuthGrantParams struct {
	UserID   uuid.UUID `json:"user_id"`
	ClientID uuid.UUID `json:"client_id"`
	Scope    string    `json:"scope"`
}

func (q *Queries) UpsertOAuthGrant(ctx context.Context, arg UpsertOAuthGrantParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, upsertOAuthGrant, arg.UserID, arg.ClientID, arg.Scope)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}
