// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ops_uptime.sql

package store

import (
	"context"
	"time"
)

const deleteOldHealthSamples = `-- name: DeleteOldHealthSamples :exec
DELETE FROM health_samples WHERE observed_at < now() - interval '100 days'
`

// Retention: 100 days — the 90-day window plus ten days of slack, so the
// oldest bar is never half-pruned and day zero always still has its anchor.
// ~29k rows steady state at the default 5-minute cadence.
func (q *Queries) DeleteOldHealthSamples(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldHealthSamples)
	return err
}

const earliestHealthSample = `-- name: EarliestHealthSample :one
SELECT observed_at FROM health_samples ORDER BY observed_at LIMIT 1
`

// The first observation ever recorded, so the pane can say "monitoring since
// <date>" and a grey bar reads as "before we were watching" rather than as an
// outage. pgx.ErrNoRows means day one, or a fresh restore.
func (q *Queries) EarliestHealthSample(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, earliestHealthSample)
	var observed_at time.Time
	err := row.Scan(&observed_at)
	return observed_at, err
}

const healthSamplesSince = `-- name: HealthSamplesSince :many
SELECT s.observed_at, s.covers_from, s.kind, s.gap_cause, s.db_ok, s.ai_ok, s.backups_ok
FROM health_samples s
WHERE s.observed_at >= COALESCE(
        (SELECT max(a.observed_at) FROM health_samples a WHERE a.observed_at < $1),
        $1)
ORDER BY s.observed_at
`

type HealthSamplesSinceRow struct {
	ObservedAt time.Time `json:"observed_at"`
	CoversFrom time.Time `json:"covers_from"`
	Kind       string    `json:"kind"`
	GapCause   *string   `json:"gap_cause"`
	DbOk       *bool     `json:"db_ok"`
	AiOk       *bool     `json:"ai_ok"`
	BackupsOk  *bool     `json:"backups_ok"`
}

// The sample stream for the graph window, plus ONE anchor row from before it.
// The anchor is load-bearing: a row covers the span ending at observed_at, so
// the row that straddles the window's opening midnight is the only evidence
// for the first minutes of day zero. Without it every window would open as
// "no data" until its first tick. Ascending — the rollup is one forward walk.
func (q *Queries) HealthSamplesSince(ctx context.Context, since time.Time) ([]HealthSamplesSinceRow, error) {
	rows, err := q.db.Query(ctx, healthSamplesSince, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthSamplesSinceRow
	for rows.Next() {
		var i HealthSamplesSinceRow
		if err := rows.Scan(
			&i.ObservedAt,
			&i.CoversFrom,
			&i.Kind,
			&i.GapCause,
			&i.DbOk,
			&i.AiOk,
			&i.BackupsOk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertHealthSample = `-- name: InsertHealthSample :exec

INSERT INTO health_samples (observed_at, covers_from, kind, release, gap_cause, db_ok, ai_ok, backups_ok)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (observed_at) DO NOTHING
`

type InsertHealthSampleParams struct {
	ObservedAt time.Time `json:"observed_at"`
	CoversFrom time.Time `json:"covers_from"`
	Kind       string    `json:"kind"`
	Release    string    `json:"release"`
	GapCause   *string   `json:"gap_cause"`
	DbOk       *bool     `json:"db_ok"`
	AiOk       *bool     `json:"ai_ok"`
	BackupsOk  *bool     `json:"backups_ok"`
}

// Uptime history for the admin Health pane's 90-day status strip
// (specs/uptime-history). Written by the health monitor (ops_monitor.go), read
// once per graph request by ops_uptime.go, pruned hourly by janitor.go.
// Nothing else touches health_samples.
// One observation interval. ON CONFLICT DO NOTHING because two writers can
// collide on the natural key: the retry buffer flushes a held sample while a
// live tick is in flight, and Postgres stores timestamptz at microsecond
// resolution. A dropped duplicate costs nothing — the rollup reads the stream,
// never an individual row.
func (q *Queries) InsertHealthSample(ctx context.Context, arg InsertHealthSampleParams) error {
	_, err := q.db.Exec(ctx, insertHealthSample,
		arg.ObservedAt,
		arg.CoversFrom,
		arg.Kind,
		arg.Release,
		arg.GapCause,
		arg.DbOk,
		arg.AiOk,
		arg.BackupsOk,
	)
	return err
}

const lastHealthSample = `-- name: LastHealthSample :one
SELECT observed_at, release FROM health_samples ORDER BY observed_at DESC LIMIT 1
`

type LastHealthSampleRow struct {
	ObservedAt time.Time `json:"observed_at"`
	Release    string    `json:"release"`
}

// The newest observation, read once at boot: its timestamp opens the boot gap,
// and its release decides whether that gap was a deploy or something
// unexplained. pgx.ErrNoRows means monitoring simply starts now.
func (q *Queries) LastHealthSample(ctx context.Context) (LastHealthSampleRow, error) {
	row := q.db.QueryRow(ctx, lastHealthSample)
	var i LastHealthSampleRow
	err := row.Scan(&i.ObservedAt, &i.Release)
	return i, err
}
