// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trip_budgets.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO trip_expenses (trip_id, category, label, amount, position, auto, source_kind, source_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, trip_id, category, label, amount, position, auto, created_at, updated_at, source_kind, source_id
`

type CreateExpenseParams struct {
	TripID     uuid.UUID   `json:"trip_id"`
	Category   string      `json:"category"`
	Label      string      `json:"label"`
	Amount     float64     `json:"amount"`
	Position   int32       `json:"position"`
	Auto       bool        `json:"auto"`
	SourceKind *string     `json:"source_kind"`
	SourceID   pgtype.UUID `json:"source_id"`
}

// auto/source_kind/source_id: the booking-autopopulate link (00061). The
// handler sets auto=true iff a source link is present — never the client.
func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (TripExpense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.TripID,
		arg.Category,
		arg.Label,
		arg.Amount,
		arg.Position,
		arg.Auto,
		arg.SourceKind,
		arg.SourceID,
	)
	var i TripExpense
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Category,
		&i.Label,
		&i.Amount,
		&i.Position,
		&i.Auto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceKind,
		&i.SourceID,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :execrows
DELETE FROM trip_expenses WHERE id = $1 AND trip_id = $2
`

type DeleteExpenseParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpense, arg.ID, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBudgetByTrip = `-- name: GetBudgetByTrip :one
SELECT id, trip_id, target_amount, currency, created_at, updated_at FROM trip_budgets WHERE trip_id = $1
`

func (q *Queries) GetBudgetByTrip(ctx context.Context, tripID uuid.UUID) (TripBudget, error) {
	row := q.db.QueryRow(ctx, getBudgetByTrip, tripID)
	var i TripBudget
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.TargetAmount,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseBySource = `-- name: GetExpenseBySource :one
SELECT id, trip_id, category, label, amount, position, auto, created_at, updated_at, source_kind, source_id FROM trip_expenses
WHERE trip_id = $1 AND source_kind = $2 AND source_id = $3
`

type GetExpenseBySourceParams struct {
	TripID     uuid.UUID   `json:"trip_id"`
	SourceKind *string     `json:"source_kind"`
	SourceID   pgtype.UUID `json:"source_id"`
}

// The upsert-by-source lookup: at most one row per booking link (partial
// unique index idx_trip_expenses_source).
func (q *Queries) GetExpenseBySource(ctx context.Context, arg GetExpenseBySourceParams) (TripExpense, error) {
	row := q.db.QueryRow(ctx, getExpenseBySource, arg.TripID, arg.SourceKind, arg.SourceID)
	var i TripExpense
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Category,
		&i.Label,
		&i.Amount,
		&i.Position,
		&i.Auto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceKind,
		&i.SourceID,
	)
	return i, err
}

const listExpensesByTrip = `-- name: ListExpensesByTrip :many
SELECT id, trip_id, category, label, amount, position, auto, created_at, updated_at, source_kind, source_id FROM trip_expenses
WHERE trip_id = $1
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListExpensesByTrip(ctx context.Context, tripID uuid.UUID) ([]TripExpense, error) {
	rows, err := q.db.Query(ctx, listExpensesByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TripExpense
	for rows.Next() {
		var i TripExpense
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Category,
			&i.Label,
			&i.Amount,
			&i.Position,
			&i.Auto,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceKind,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE trip_expenses
SET category = COALESCE($1, category),
    label    = COALESCE($2, label),
    amount   = COALESCE($3, amount),
    position = COALESCE($4, position),
    auto     = COALESCE($5, auto)
WHERE id = $6 AND trip_id = $7
RETURNING id, trip_id, category, label, amount, position, auto, created_at, updated_at, source_kind, source_id
`

type UpdateExpenseParams struct {
	Category *string   `json:"category"`
	Label    *string   `json:"label"`
	Amount   *float64  `json:"amount"`
	Position *int32    `json:"position"`
	Auto     *bool     `json:"auto"`
	ID       uuid.UUID `json:"id"`
	TripID   uuid.UUID `json:"trip_id"`
}

// Partial update (COALESCE sqlc.narg idiom, see query/trip_checklist_items.sql
// UpdateChecklistItem). COALESCE means a field can be overwritten but not
// cleared to NULL (auto IS NOT NULL, so narg('auto') skips it when nil —
// the handler passes false on a user content edit: manual takeover).
func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (TripExpense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.Category,
		arg.Label,
		arg.Amount,
		arg.Position,
		arg.Auto,
		arg.ID,
		arg.TripID,
	)
	var i TripExpense
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Category,
		&i.Label,
		&i.Amount,
		&i.Position,
		&i.Auto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceKind,
		&i.SourceID,
	)
	return i, err
}

const upsertBudget = `-- name: UpsertBudget :one
INSERT INTO trip_budgets (trip_id, target_amount, currency)
VALUES ($1, $2, $3)
ON CONFLICT (trip_id) DO UPDATE
SET target_amount = EXCLUDED.target_amount,
    currency      = EXCLUDED.currency
RETURNING id, trip_id, target_amount, currency, created_at, updated_at
`

type UpsertBudgetParams struct {
	TripID       uuid.UUID `json:"trip_id"`
	TargetAmount *float64  `json:"target_amount"`
	Currency     string    `json:"currency"`
}

// One budget per trip: insert, or overwrite the target/currency of the existing
// row (trip_id is UNIQUE). updated_at is bumped by the set_updated_at trigger.
func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) (TripBudget, error) {
	row := q.db.QueryRow(ctx, upsertBudget, arg.TripID, arg.TargetAmount, arg.Currency)
	var i TripBudget
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.TargetAmount,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
