#!/usr/bin/env bash
#
# worktree.sh — parallel "lane" worktrees, each with its own branch, port slot,
# and dev stack (see the Makefile wt-* targets that wrap this).
#
# A lane's config lives in .wt.env at the worktree root (gitignored). The
# Makefile -includes and exports it, and dockerize/development/docker-compose.yml
# interpolates it, so slot N gets project gtt-<name>, gateway 3000+N, and
# postgres 5432+N with its own volume/network. Slot 0 (no .wt.env) is the main
# checkout's single stack on 3000/5432.
#
# Usage:
#   worktree.sh new NAME [--slot N]    create worktree + branch NAME off origin/main
#   worktree.sh init [--slot N]        provision the CURRENT worktree in place
#                                      (for harness-created agent worktrees)
#   worktree.sh rm NAME [--force]      worktree + branch removed, stack down -v
#                                      (--force also unlocks harness worktrees)
#   worktree.sh list                   worktrees, slots, ports, running stacks
#   worktree.sh prune [--yes]          list (and with --yes delete) orphaned
#                                      dirs under .claude/worktrees

set -euo pipefail

die() { echo "error: $*" >&2; exit 1; }

# Main checkout = first entry of `git worktree list` (git guarantees order).
MAIN=$(git worktree list --porcelain | head -1 | sed 's/^worktree //')
[ -n "$MAIN" ] || die "not inside a git repository"
WT_ROOT="$MAIN/.claude/worktrees"

sanitize() { # branch/dir name -> compose-safe project suffix
  printf '%s' "$1" | tr '[:upper:]/' '[:lower:]-' | tr -c 'a-z0-9-' '-' \
    | sed -e 's/--*/-/g' -e 's/^-*//' -e 's/-*$//'
}

registered_paths() { git worktree list --porcelain | sed -n 's/^worktree //p'; }

lane_env() { # $1 = worktree path, $2 = key
  sed -n "s/^$2=//p" "$1/.wt.env" 2>/dev/null || true
}

used_slots() {
  registered_paths | while read -r p; do
    [ -f "$p/.wt.env" ] && lane_env "$p" GTT_SLOT || true
  done
}

next_slot() {
  local n=1
  while used_slots | grep -qx "$n"; do n=$((n + 1)); done
  echo "$n"
}

# Slot/project allocation reads other lanes' .wt.env files and only commits by
# writing its own — two concurrent new/init calls would race to the same slot
# without this mkdir lock (atomic on every filesystem, bash-3.2 safe).
lock_alloc() {
  mkdir -p "$WT_ROOT"
  local i=0
  until mkdir "$WT_ROOT/.lock" 2>/dev/null; do
    i=$((i + 1))
    [ "$i" -lt 50 ] || die "allocation lock busy — remove $WT_ROOT/.lock if stale"
    sleep 0.2
  done
  trap 'rmdir "$WT_ROOT/.lock" 2>/dev/null || true' EXIT
}

ensure_free() { # $1 = slot, $2 = project, $3 = self path ("" = none) — die on conflict
  case "$1" in ('' | *[!0-9]*) die "slot must be a number, got '$1'";; esac
  [ "$1" -ge 1 ] || die "slot must be >= 1 (slot 0 is the main checkout)"
  local p
  while read -r p; do
    [ -n "$p" ] && [ "$p" != "$3" ] && [ -f "$p/.wt.env" ] || continue
    [ "$(lane_env "$p" GTT_SLOT)" != "$1" ] \
      || die "slot $1 is already taken by $p (see: worktree.sh list)"
    [ "$(lane_env "$p" GTT_PROJECT)" != "$2" ] \
      || die "project '$2' is already used by $p — pick a different lane name"
  done <<EOF
$(registered_paths)
EOF
}

provision() { # $1 = worktree path, $2 = slot
  local wt=$1 slot=$2 proj envfile tmp
  proj="gtt-$(sanitize "$(basename "$wt")")"
  [ "$proj" != "gtt-" ] || die "cannot derive a project name from '$wt'"
  ensure_free "$slot" "$proj" "$wt"

  # .env is gitignored — without this copy the lane's API boots keyless/degraded.
  if [ -f "$MAIN/src/packages/api/.env" ] && [ ! -f "$wt/src/packages/api/.env" ]; then
    cp "$MAIN/src/packages/api/.env" "$wt/src/packages/api/.env"
    # Retarget gateway-port URLs at this lane: the API defaults PUBLIC_BASE_URL
    # to http://localhost:3000 when unset, which breaks MCP/OAuth discovery and
    # SSO redirects on any other slot. (tmp-file sed: BSD/GNU -i differ.)
    envfile="$wt/src/packages/api/.env"
    tmp=$(mktemp)
    sed -e "s|localhost:3000|localhost:$((3000 + slot))|g" \
        -e "s|localhost:5432|localhost:$((5432 + slot))|g" \
        "$envfile" > "$tmp" && mv "$tmp" "$envfile"
    if ! grep -q '^PUBLIC_BASE_URL=' "$envfile"; then
      printf 'PUBLIC_BASE_URL=http://localhost:%s\n' "$((3000 + slot))" >> "$envfile"
    fi
  fi

  cat > "$wt/.wt.env" <<EOF
# generated by scripts/worktree.sh — per-worktree dev-stack config (gitignored)
GTT_SLOT=$slot
GTT_PROJECT=$proj
GTT_GATEWAY_PORT=$((3000 + slot))
GTT_PG_PORT=$((5432 + slot))
TEST_DATABASE_URL=postgres://travel:travel@localhost:$((5432 + slot))/travel_planner_test?sslmode=disable
EOF

  # A branch that predates the compose `name:` parameterization would ignore
  # GTT_* entirely and fight the main checkout's stack for the "development"
  # project — warn loudly rather than let `make docker-dev` collide.
  if ! grep -q 'GTT_PROJECT' "$wt/dockerize/development/docker-compose.yml" 2>/dev/null; then
    echo "WARNING: this worktree's dev compose is NOT parameterized (branch predates" >&2
    echo "         parallel lanes). Do not run docker targets here — rebase onto main first." >&2
  fi

  cat <<EOF
lane ready: $wt
  project  $proj
  gateway  http://localhost:$((3000 + slot))
  postgres localhost:$((5432 + slot))
next:
  cd $wt
  make docker-dev-bg   # own stack on the ports above
  make test-db         # per-lane integration-test DB
  make smoke           # e2e against this lane's gateway
(make reads .wt.env automatically; for bare docker/go commands: set -a; . .wt.env; set +a)
EOF
}

cmd_new() {
  local name=${1:-} slot=""
  [ -n "$name" ] || die "usage: worktree.sh new NAME [--slot N]"
  shift
  while [ $# -gt 0 ]; do
    case "$1" in
      (--slot) slot=${2:-}; shift 2 ;;
      (*) die "unknown option '$1'" ;;
    esac
  done
  local dir proj
  dir="$WT_ROOT/$(printf '%s' "$name" | tr '/' '-')"
  [ ! -e "$dir" ] || die "$dir already exists"
  proj="gtt-$(sanitize "$(basename "$dir")")"
  [ "$proj" != "gtt-" ] || die "cannot derive a project name from '$name'"
  lock_alloc
  slot=${slot:-$(next_slot)}
  # Validate BEFORE git worktree add — a slot error must not strand a half-made lane.
  ensure_free "$slot" "$proj" ""
  git -C "$MAIN" fetch origin main 2>/dev/null \
    || echo "warn: fetch failed — branching from local main" >&2
  local base=origin/main
  git -C "$MAIN" rev-parse --verify -q "$base" >/dev/null || base=main
  git -C "$MAIN" worktree add -b "$name" "$dir" "$base"
  provision "$dir" "$slot"
}

cmd_init() {
  local slot=""
  while [ $# -gt 0 ]; do
    case "$1" in
      (--slot) slot=${2:-}; shift 2 ;;
      (*) die "unknown option '$1'" ;;
    esac
  done
  local top; top=$(git rev-parse --show-toplevel)
  [ "$top" != "$MAIN" ] || die "this is the main checkout (slot 0, default ports) — init is for worktrees"
  lock_alloc
  provision "$top" "${slot:-$(next_slot)}"
}

cmd_rm() {
  local name=${1:-} force=""
  [ -n "$name" ] || die "usage: worktree.sh rm NAME [--force]"
  shift
  while [ $# -gt 0 ]; do
    case "$1" in
      (--force) force=1; shift ;;
      (*) die "unknown option '$1'" ;;
    esac
  done
  local dir proj branch="" is_reg=""
  dir="$WT_ROOT/$(printf '%s' "$name" | tr '/' '-')"
  proj="gtt-$(sanitize "$(basename "$dir")")"
  if [ -f "$dir/.wt.env" ]; then
    proj=$(lane_env "$dir" GTT_PROJECT)
  fi
  if registered_paths | grep -qxF "$dir"; then
    is_reg=1
    branch=$(git worktree list --porcelain | grep -A2 "^worktree $dir\$" \
      | sed -n 's|^branch refs/heads/||p')
  fi
  # A name that was never a lane must not fall through to the branch delete.
  [ -d "$dir" ] || [ -n "$is_reg" ] || die "no such lane: $dir (see: worktree.sh list)"

  # Remove the worktree FIRST: git refuses while real uncommitted work exists
  # (.wt.env and the copied .env are gitignored and don't block), so nothing
  # is destroyed on refusal. Harness-created worktrees are locked and need a
  # second --force to remove.
  if [ -d "$dir" ]; then
    [ -n "$is_reg" ] \
      || die "$dir exists but is not a registered worktree — worktree.sh prune handles orphans"
    if [ -n "$force" ]; then
      git -C "$MAIN" worktree remove --force --force "$dir"
    else
      git -C "$MAIN" worktree remove "$dir"
    fi
  else
    git -C "$MAIN" worktree prune
  fi

  # Label-based teardown (-p, never -f): the worktree's own compose file can't
  # be trusted — on a branch predating the `name:` parameterization it resolves
  # to the MAIN stack's "development" project and would down that instead.
  # Belt and suspenders: only ever tear down lane (gtt-*) projects.
  case "$proj" in
    (gtt-?*) docker compose -p "$proj" down --volumes --remove-orphans 2>/dev/null || true ;;
    (*) echo "warn: project '$proj' is not a lane (gtt-*) — skipping stack teardown" >&2 ;;
  esac

  if [ -n "${branch:-$name}" ]; then
    git -C "$MAIN" branch -d "${branch:-$name}" 2>/dev/null \
      || echo "branch '${branch:-$name}' not deleted (unmerged or missing) — git branch -D if you're sure" >&2
  fi
  echo "removed: $dir (project $proj)"
}

cmd_list() {
  printf '%-14s %-40s %-6s %-9s %s\n' SLOT PATH GW PG BRANCH
  local p="" branch=""
  git worktree list --porcelain | while read -r key val; do
    case "$key" in
      (worktree) p=$val ;;
      (branch) branch=${val#refs/heads/} ;;
      ('')
        local slot="0" gw="3000" pg="5432"
        if [ -f "$p/.wt.env" ]; then
          slot=$(lane_env "$p" GTT_SLOT)
          gw=$(lane_env "$p" GTT_GATEWAY_PORT)
          pg=$(lane_env "$p" GTT_PG_PORT)
        fi
        printf '%-14s %-40s %-6s %-9s %s\n' "$slot" "$p" "$gw" "$pg" "${branch:-?}"
        p="" branch="" ;;
    esac
  done
  echo
  echo "running compose projects:"
  docker compose ls 2>/dev/null | grep -E '^(NAME|development|gtt-)' || echo "  (docker not running)"
}

cmd_prune() {
  local yes=""
  [ "${1:-}" != "--yes" ] || yes=1
  git -C "$MAIN" worktree prune -v
  [ -d "$WT_ROOT" ] || { echo "nothing to prune"; return 0; }
  local found=""
  for d in "$WT_ROOT"/*/; do
    [ -d "$d" ] || continue
    d=${d%/}
    registered_paths | grep -qxF "$d" && continue
    found=1
    if [ -n "$yes" ]; then
      rm -rf "$d" && echo "deleted: $d"
    else
      printf 'orphaned: %-60s %s\n' "$d" "$(du -sh "$d" 2>/dev/null | cut -f1)"
    fi
  done
  if [ -n "$found" ] && [ -z "$yes" ]; then
    echo
    echo "orphaned dirs are NOT registered worktrees — git cannot verify they are clean."
    echo "eyeball anything you care about, then: worktree.sh prune --yes"
  fi
  [ -n "$found" ] || echo "no orphaned dirs"
}

case "${1:-}" in
  (new)   shift; cmd_new "$@" ;;
  (init)  shift; cmd_init "$@" ;;
  (rm)    shift; cmd_rm "$@" ;;
  (list)  shift; cmd_list "$@" ;;
  (prune) shift; cmd_prune "${1:-}" ;;
  (*) sed -n '2,21p' "$0" | sed 's/^# \{0,1\}//'; exit 1 ;;
esac
