// GENERATED by scripts/fetch-destination-photos.py — do not edit.
// Re-run that script to change a destination photo or its credit;
// it rewrites the .webp files, CREDITS.md, and this table together,
// which is what stops the on-card attribution from drifting away
// from the image that actually shipped.

/// A bundled destination photo: its asset path and the short credit
/// rendered over it. Full attribution lives in
/// assets/images/destinations/CREDITS.md.
class DestinationPhoto {
  final String asset;
  final String credit;

  const DestinationPhoto(this.asset, this.credit);
}

/// Keyed by the slug each suggestion prompt names in `suggestionPool`.
const Map<String, DestinationPhoto> kDestinationPhotos = {
  'amalfi': DestinationPhoto(
    'assets/images/destinations/amalfi.webp',
    'Bernard Gagnon / CC BY 4.0',
  ),
  'bali': DestinationPhoto(
    'assets/images/destinations/bali.webp',
    'Chainwit / CC BY 4.0',
  ),
  'bangkok': DestinationPhoto(
    'assets/images/destinations/bangkok.webp',
    'Radosław Botev / CC BY 3.0 pl',
  ),
  'barcelona': DestinationPhoto(
    'assets/images/destinations/barcelona.webp',
    'Dungodung / Public domain',
  ),
  'greece': DestinationPhoto(
    'assets/images/destinations/greece.webp',
    'karol m / CC BY 2.0',
  ),
  'kenya': DestinationPhoto(
    'assets/images/destinations/kenya.webp',
    'Ray in Manila / CC BY 2.0',
  ),
  'lisbon': DestinationPhoto(
    'assets/images/destinations/lisbon.webp',
    'Jorge Franganillo / CC BY 2.0',
  ),
  'newyork': DestinationPhoto(
    'assets/images/destinations/newyork.webp',
    'Jakub Hałun / CC BY 4.0',
  ),
  'paris': DestinationPhoto(
    'assets/images/destinations/paris.webp',
    'Pedro Kümmel / CC0',
  ),
  'patagonia': DestinationPhoto(
    'assets/images/destinations/patagonia.webp',
    'Prissantenbär / Public domain',
  ),
  'rome': DestinationPhoto(
    'assets/images/destinations/rome.webp',
    'Wilfredor / CC0',
  ),
  'tokyo': DestinationPhoto(
    'assets/images/destinations/tokyo.webp',
    'David Kernan / CC BY 4.0',
  ),
};
